#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

# TODO: we should really try to determine if nipapd is installed on this
# machine here, but as packages are not yet guaranteed to be unpacked in the
# config stage we cannot determine if nipapd is or is going to be installed by
# looking if files exists. Can we ask apt?

db_input high nipap-www/auto_secret_key || true
db_go
