#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

WWW_USER='www-user'
WWW_PASS=`</dev/urandom tr -dc [:alpha:] | head -c16`
WWW_NAME='User for the Web UI'

# TODO: it's probably very wrong to ask questions in the postinst step of the
# installation but we know of no better way for the moment.. also see the
# config file.

# determine if nipapd is installed on this machine
if [ -e /etc/nipap/local_auth.db ]; then
	db_input high nipap-www/autouser || true
	db_go
fi

db_get nipap-www/autouser
if [ "$RET" = "true" ]; then
	echo "Adding new user!!!"
	# check if www-user already exists, if not, create it and configure it in
	# the nipap.conf configuration file, provided that it exists
	if [ `nipap-passwd -l | awk "{ if (\\$1~/^$WWW_USER$/) { print \\$1 } }" | wc -l` = "0" ]; then
		nipap-passwd -a $WWW_USER -p $WWW_PASS -n "$WWW_NAME"
		if [ -e /etc/nipap/nipap.conf ]; then
			sed -i -e "s/http:\/\/[^:]\+:[^@]\+@/http:\/\/$WWW_USER@local:$WWW_PASS@/" /etc/nipap/nipap.conf
		fi
	fi
fi
