#!/bin/sh -e

### BEGIN INIT INFO
# Provides:	nipapd
# Required-Start:	$postgresql
# Required-Stop:	$postgresql
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	NIPAP XML-RPC server
### END INIT INFO

DAEMON=/usr/sbin/nipapd
DAEMON=/home/kll/kod/NIPAP/nipap/nipapd
DAEMON=/usr/bin/nipapd
CONFIGFILE=/home/kll/kod/NIPAP/nipap/kll.conf
NAME=NIPAPd
PIDFILE=/var/run/nipapd.pid

. /lib/lsb/init-functions

running() {
	if [ $(flock -xn $PIDFILE -c 'echo 1') ]; then 
		echo -n
	else
		cat $PIDFILE
	fi
}


case "$1" in
	start)
		log_daemon_msg "Starting NIPAPd XML-RPC server" "nipapd"
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			log_progress_msg "already running"
			log_end_msg 0
		else
			if start-stop-daemon --start --exec $DAEMON -- -c $CONFIGFILE; then
				log_end_msg 0
			else
				log_end_msg 1
			fi
		fi
		;;
	stop)
		log_daemon_msg "Stopping NIPAPd XML-RPC server" "nipapd"
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			if start-stop-daemon --stop --pidfile $PIDFILE --retry 30; then
				log_end_msg 0
			else
				log_end_msg 1
			fi
		else
			log_end_msg 0
		fi
		;;
	reload)
		log_daemon_msg "Reloading NIPAPd XML-RPC server's configuration" "nipapd"
		;;
	restart)
		log_daemon_msg "Restarting NIPAPd XML-RPC server" "nipapd"
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			if start-stop-daemon --stop --pidfile $PIDFILE; then
				if start-stop-daemon --start --exec $DAEMON -- -c $CONFIGFILE; then
					log_end_msg 0
				else
					log_end_msg 1
				fi
			else
				log_end_msg 1
			fi
		else
			if start-stop-daemon --start --exec $DAEMON -- -c $CONFIGFILE; then
				log_end_msg 0
			else
				log_end_msg 1
			fi
		fi
		;;
	status)
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			log_action_msg "NIPAPd XML-RPC server running with PID $RUNNING"
		else
			log_action_msg "NIPAPd XML-RPC not running"
		fi
		;;
	*)
		log_action_msg "Usage: /etc/init.d/nipapd {start|stop|restart|reload|status}"
esac

exit 0
