#! /usr/bin/python
""" NIPAP shell command

    A shell command to interact with NIPAP.
"""

import sys

from nipap_cli import nipap_cli
from nipap_cli.command import Command
from pynipap import NipapError


if __name__ == '__main__':

    try:
        cmd = Command(nipap_cli.cmds, sys.argv[1::])
    except ValueError, e:
        print >> sys.stderr, "Error: %s" % e.message
        sys.exit(1)

    # execute command
    if cmd.exe is None:
        print "Incomplete command specified"
        print "valid completions: %s" % " ".join(cmd.next_values())
        sys.exit(1)

    try:
        cmd.exe(cmd.arg, cmd.exe_options)
    except NipapError, e:
        print >> sys.stderr, "Command failed:\n  %s" % e.message
        sys.exit(1)

