#! /usr/bin/python
""" NIPAP shell command

    A shell command to interact with NIPAP.
"""

import sys

import nipap_cli
from command import Command
from pynipap import NipapError


__version__     = "0.1.0"
__author__      = "Kristian Larsson, Lukas Garberg"
__author_email__ = "kll@tele2.net, lukas@spritelink.net"
__license__     = "MIT"
__status__      = "Development"
__url__         = "http://github.com/plajjan/NIPAP"


if __name__ == '__main__':

    try:
        cmd = Command(nipap_cli.cmds, sys.argv[1::])
    except ValueError, e:
        print >> sys.stderr, "Error: %s" % e.message
        sys.exit(1)

    # execute command
    if cmd.exe is None:
        print "Incomplete command specified"
        print "valid completions: %s" % " ".join(cmd.next_values())
        sys.exit(1)

    try:
        cmd.exe(cmd.arg, cmd.exe_options)
    except NipapError, e:
        print >> sys.stderr, "Command failed:\n  %s" % e.message
        sys.exit(1)

