#! /usr/bin/python

""" CLI command completion helper

    nipap_helper.py is used to provide tab completion capabilities of nipap
    commands to for example bash.
"""

import sys
import os
from nipap_cli.command import Command
from nipap_cli import nipap_cli
from pynipap import NipapError


__author__      = "Kristian Larsson, Lukas Garberg"
__author_email__ = "kll@tele2.net, lukas@spritelink.net"
__license__     = "MIT"
__status__      = "Development"
__url__         = "http://github.com/plajjan/NIPAP"


if __name__ == '__main__':

    cmd = Command(nipap_cli.cmds, sys.argv[1::])

    comp = []

    try:
        comp = sorted(cmd.complete())
    except NipapError:
        # handle errors silently
        pass

    for val in comp:
        print val
