#! /usr/bin/python
#
# Manages NIPAP LocalAuth authentication database
#

import sys
import os
import optparse
import logging

import nipap.authlib
from nipap.nipapconfig import NipapConfig, NipapConfigError

if __name__ == '__main__':

    # parse options
    parser = optparse.OptionParser()
    parser.add_option('-a', '--add', dest='add_user', type='string', help='add user ADD_USER')
    parser.add_option('-c', '--config', dest='config', default='/etc/nipap/nipap.conf', type='string',
            help='read configuration from CONFIG [default:/etc/nipap/nipap.conf]')
    parser.add_option('--create-database', action='store_true',
            help='create SqliteAuth database')
    parser.add_option('-d', '--delete', dest='delete_user', type='string', help="delete user DELETE_USER")
    parser.add_option('-f', '--file', dest='db_file', type='string', help="database file [default: read from config]")
#    parser.add_option('-m', '--modify', dest='modify_user', type='string')
    parser.add_option('-n', '--name', dest='name', type='string', help='set user\'s name to NAME')
    parser.add_option('--latest-version', action='store_true',
            help='check if the sqlite database is of latest version')
    parser.add_option('-l', '--list', action='store_true', dest='list', help='list users')
    parser.add_option('-p', '--password', dest='password', type='string', help='set user\'s password to PASSWORD')
    parser.add_option('-r', '--readonly', action='store_true', dest='readonly', default=False, help='set user to read only')
    parser.add_option('-t', '--trusted', action='store_true', dest='trusted', default=False, help='mark user as trusted')
    parser.add_option('--upgrade-database', action='store_true',
            help='upgrade sqlite database to latest version')
    options, args = parser.parse_args()

    logger = logging.getLogger()
    log_format = "%(levelname)-8s %(message)s"
    log_stream = logging.StreamHandler()
    log_stream.setFormatter(logging.Formatter("%(asctime)s: " + log_format))
    logger.setLevel(logging.WARNING)
    logger.addHandler(log_stream)

    try:
        cfg = NipapConfig(options.config)
    except NipapConfigError, exc:
        print >> sys.stderr, "The specified configuration file ('" + options.config + "') does not exist"
        sys.exit(1)

    if options.db_file:
        cfg.set('auth.backends.local', 'db_path', options.db_file)

    a = nipap.authlib.SqliteAuth('local', 'a', 'b', 'c')

    if options.latest_version:
        try:
            a._latest_db_version()
        except nipap.authlib.AuthSqliteError, e:
            print >> sys.stderr, "Problem with Sqlite database for local auth: %s" % e
            print >> sys.stderr, "Run 'nipap-passwd --upgrade-database' to upgrade your database."
            sys.exit(1)
        print "Sqlite database for local auth is of the latest version."
        sys.exit(0)

    if options.create_database:
        a._create_database()
        sys.exit(0)

    if options.upgrade_database:
        a._upgrade_database()
        sys.exit(0)

    if options.list:
        # print a nicely formatted list of users
        header =  "%-20s %-25s %-7s %-7s" % ('username', 'real name', 'trusted', 'read only')
        print "%s\n%s" % (header,''.join('-' for x in range(len(header))))
        for u in a.list_users():
            print "%-20s %-25s %-7d %-7d" % (u['username'], u['full_name'], int(u['trusted']), int(u['readonly']))

    elif options.add_user:
        if not options.password:
            print "Please specify password with --password"
            sys.exit(1)
        if not options.name:
            print "Please specify name with --name"
            sys.exit(1)
        try:
            a.add_user(options.add_user, options.password, options.name, options.trusted, options.readonly)
            print "Added user %s to database %s" % (options.add_user, cfg.get('auth.backends.local','db_path'))
        except nipap.authlib.AuthError as exc:
            if str(exc) == 'attempt to write a readonly database':
                print "You do not have sufficient rights to write to database: %s" % (cfg.get('auth.backends.local','db_path'))
            elif str(exc) == 'column username is not unique':
                print "Username '%s' already exists in the database: %s " % (options.add_user, cfg.get('auth.backends.local','db_path'))
            else:
                print exc
    elif options.delete_user:
        try:
            a.remove_user(options.delete_user)
            print "User %s deleted from database %s" % (options.delete_user, cfg.get('auth.backends.local', 'db_path'))
        except nipap.authlib.AuthError as exc:
            if str(exc) == 'attempt to write a readonly database':
                print "You do not have sufficient rights to write to database: %s" % (cfg.get('auth.backends.local','db_path'))
            else:
                print exc

    else:
        parser.print_help()
