#!/bin/sh

set -e

### BEGIN INIT INFO
# Provides:	nipap-whoisd
# Required-Start:	$remote_fs $network
# Required-Stop:	$remote_fs $network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	NIPAP whois daemon
### END INIT INFO

DAEMON=/usr/sbin/nipap-whoisd
CONFIGFILE=/etc/nipap/whoisd.conf
NAME=nipap-whoisd
LONGNAME="NIPAP whois daemon"
PIDFILE=/var/run/nipap-whoisd/whoisd.pid
PIDDIR=`dirname $PIDFILE`
DEFAULTS=/etc/default/nipap-whoisd

. /lib/lsb/init-functions

RUN=no
# include defaults if available
if [ -f $DEFAULTS ]; then
	. $DEFAULTS
fi

if [ "$RUN" != "yes" ]; then
	log_action_msg "$NAME disabled; edit $DEFAULTS"
	exit 0
fi

running() {
	# create dir for PID file if it doesn't exist
	if [ ! -d "$PIDDIR" ]; then
		mkdir "$PIDDIR"
		chown nobody:nogroup $PIDDIR
	fi

	if [ $(flock -xn $PIDFILE -c 'echo 1' 2> /dev/null) ]; then
		echo -n
		rm -f $PIDFILE > /dev/null 2>&1
	else
		cat $PIDFILE || echo -n
	fi
}


case "$1" in
	start)
		log_daemon_msg "Starting $LONGNAME" "$NAME"
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			log_progress_msg "already running"
			log_end_msg 0
		else
			if start-stop-daemon --start --exec $DAEMON -- --config $CONFIGFILE; then
				log_end_msg 0
			else
				log_end_msg 1
			fi
		fi
		;;
	stop)
		log_daemon_msg "Stopping $LONGNAME" "$NAME"
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			if start-stop-daemon --stop --pidfile $PIDFILE --retry 30; then
				log_end_msg 0
			else
				log_end_msg 1
			fi
		else
			log_end_msg 0
		fi
		;;
	restart)
		log_daemon_msg "Restarting $LONGNAME" "$NAME"
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			if start-stop-daemon --stop --pidfile $PIDFILE; then
				if start-stop-daemon --start --exec $DAEMON -- --config $CONFIGFILE; then
					log_end_msg 0
				else
					log_end_msg 1
				fi
			else
				log_end_msg 1
			fi
		else
			if start-stop-daemon --start --exec $DAEMON -- --config $CONFIGFILE; then
				log_end_msg 0
			else
				log_end_msg 1
			fi
		fi
		;;
	status)
		RUNNING=$(running)
		if [ -n "$RUNNING" ]; then
			log_success_msg "$LONGNAME running with PID $RUNNING"
			exit 0
		else
			log_failure_msg "$LONGNAME not running"
			exit 3
		fi
		;;
	*)
		log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
esac

exit 0
